# Generated by Django 3.1.4 on 2020-12-28 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LastFMChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_position', models.PositiveSmallIntegerField()),
                ('track_name', models.CharField(max_length=100)),
                ('author_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'LastFM Chart',
                'db_table': 'lastfm_chart',
            },
        ),
        migrations.CreateModel(
            name='SpotifyChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_position', models.PositiveSmallIntegerField()),
                ('track_name', models.CharField(max_length=100)),
                ('author_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Spotyfy Chart',
                'db_table': 'spotify_chart',
            },
        ),
        migrations.CreateModel(
            name='YandexMusicChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_position', models.PositiveSmallIntegerField()),
                ('track_name', models.CharField(max_length=100)),
                ('author_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Yandex Music Chart',
                'db_table': 'yandex_music_chart',
            },
        ),
    ]
